# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    branches: main
  schedule:
    - cron: '0 6 * * *'


name: render website

jobs:
  render:
    name: Rebuild Website
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-pandoc@v2
      
      - name: Install rmarkdown
        run: Rscript -e 'install.packages("rmarkdown")'
      - name: Install tidyverse
        run: Rscript -e 'install.packages("tidyverse")'
      - name: Install httr
        run: Rscript -e 'install.packages("httr")'
      - name: Install jsonlite
        run: Rscript -e 'install.packages("jsonlite")'
      - name: Install rtide
        run: Rscript -e 'install.packages("rtide")'
      - name: Install glue
        run: Rscript -e 'install.packages("glue")'
      - name: Install lubridate
        run: Rscript -e 'install.packages("lubridate")'
      - name: Install ggmisc
        run: Rscript -e 'install.packages("ggpmisc")'
      - name: Install htmltools
        run: Rscript -e 'install.packages("htmltools")'

      - name: Render Rmarkdown files and Commit Results
        env: 
          WEATHER: ${{ secrets.WEATHER }}
        run: |
          echo "Rendering the page..."
          Rscript -e 'rmarkdown::render(input = "index.Rmd")'
          if [[ "$(git status --porcelain)" != "" ]]; then
            git config --local user.name "$GITHUB_ACTOR"
            git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
            git add *
            git commit -m "Auto update Report"
            git push origin
          fi
